"""SQLAlchemy models for every RADAR table.

One model per table in the schema (docs/architecture/data-model.md and the
implementation plan): alerts, incidents, investigation_plans, recommendations,
feedback, outbox_events, processed_events, runbook_documents, audit_log.

Column types, lengths, nullability, server defaults, foreign keys, and index
names mirror the DDL exactly so the Alembic autogenerated migration matches the
intended schema. UUID primary keys default to ``gen_random_uuid()`` and
timestamps to ``now()`` on the database side; ``updated_at`` columns are set
explicitly by the application (matching the plan), not by a trigger.
"""

# NOTE: no ``from __future__ import annotations`` here. SQLAlchemy declarative
# reads the ``Mapped[...]`` annotations at mapper-configuration time; stringized
# annotations force it down a de-stringify path that is broken for ``X | None``
# unions on Python 3.14 + SQLAlchemy 2.0.36. Real annotations avoid it.

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    PrimaryKeyConstraint,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

_GEN_UUID = "gen_random_uuid()"


class Base(DeclarativeBase):
    """Declarative base for all RADAR tables."""


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    source: Mapped[str] = mapped_column(String(64), nullable=False)
    source_alert_id: Mapped[str | None] = mapped_column(String(256))
    fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    service_name: Mapped[str] = mapped_column(String(128), nullable=False)
    alert_name: Mapped[str] = mapped_column(String(256), nullable=False)
    severity: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default=text("'firing'")
    )
    raw_payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    labels: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    annotations: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    fired_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    incident_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("incidents.id", deferrable=True, initially="DEFERRED"),
    )
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )

    __table_args__ = (
        Index("idx_alerts_fingerprint", "fingerprint"),
        Index("idx_alerts_incident_id", "incident_id"),
        Index("idx_alerts_service_name", "service_name"),
        Index("idx_alerts_fired_at", text("fired_at DESC")),
        Index("idx_alerts_status", "status"),
        Index("idx_alerts_correlation_id", "correlation_id"),
    )


class Incident(Base):
    __tablename__ = "incidents"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, unique=True
    )
    fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    service_name: Mapped[str] = mapped_column(String(128), nullable=False)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    severity: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default=text("'open'")
    )
    alert_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1")
    )
    opened_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # updated_at: set in app code, not via onupdate - visible at the call site.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_incidents_fingerprint", "fingerprint"),
        Index("idx_incidents_status", "status"),
        Index("idx_incidents_service_name", "service_name"),
        Index("idx_incidents_opened_at", text("opened_at DESC")),
        Index("idx_incidents_correlation_id", "correlation_id"),
    )


class InvestigationPlan(Base):
    __tablename__ = "investigation_plans"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("incidents.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    steps: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)
    template_key: Mapped[str | None] = mapped_column(String(128))
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default=text("'pending'")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # updated_at: set in app code, not via onupdate - visible at the call site.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_plans_incident_id", "incident_id"),
        Index("idx_plans_one_per_incident", "incident_id", unique=True),
    )


class Recommendation(Base):
    __tablename__ = "recommendations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("incidents.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    plan_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("investigation_plans.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    llm_provider: Mapped[str] = mapped_column(String(64), nullable=False)
    model_alias: Mapped[str] = mapped_column(String(64), nullable=False)
    model_id: Mapped[str] = mapped_column(String(128), nullable=False)
    root_cause: Mapped[str] = mapped_column(Text, nullable=False)
    confidence: Mapped[str] = mapped_column(String(16), nullable=False)
    recommended_actions: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False
    )
    context_bundle: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    raw_llm_response: Mapped[str | None] = mapped_column(Text)
    is_fallback: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false")
    )
    prompt_tokens: Mapped[int | None] = mapped_column(Integer)
    completion_tokens: Mapped[int | None] = mapped_column(Integer)
    latency_ms: Mapped[int | None] = mapped_column(Integer)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_rec_incident_id", "incident_id"),
        # ONE recommendation per incident, mirroring idx_plans_one_per_incident.
        #
        # Not in the plan's DDL, and added deliberately. An incident gets exactly one
        # RCA: a second recommendation means the engineer receives two contradictory
        # Slack cards for one incident and cannot tell which is current. The reasoner
        # is the only stage that spends money, so the redelivery that would produce a
        # duplicate is also the one that charges twice.
        #
        # The reasoner's dispatch timeout is ordered against its LLM budget precisely
        # so that race cannot happen (radar_common.timeouts) — this index is the
        # backstop for when it does anyway: a crash mid-call, a manual requeue of a
        # dead letter, an operator replaying an event. The guarantee then rests on the
        # SCHEMA rather than on two numbers staying in the right order forever.
        Index("idx_rec_one_per_incident", "incident_id", unique=True),
        Index("idx_rec_plan_id", "plan_id"),
        Index("idx_rec_created_at", text("created_at DESC")),
        Index("idx_rec_correlation", "correlation_id"),
        Index("idx_rec_is_fallback", "is_fallback"),
    )


class Feedback(Base):
    __tablename__ = "feedback"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    recommendation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("recommendations.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    incident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("incidents.id", deferrable=True, initially="DEFERRED"),
        nullable=False,
    )
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    sentiment: Mapped[str] = mapped_column(String(16), nullable=False)
    correction_text: Mapped[str | None] = mapped_column(Text)
    slack_user_id: Mapped[str | None] = mapped_column(String(64))
    slack_message_ts: Mapped[str | None] = mapped_column(String(64))
    llm_provider: Mapped[str] = mapped_column(String(64), nullable=False)
    model_alias: Mapped[str] = mapped_column(String(64), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_feedback_recommendation_id", "recommendation_id"),
        Index("idx_feedback_incident_id", "incident_id"),
        Index("idx_feedback_sentiment", "sentiment"),
        Index("idx_feedback_created_at", text("created_at DESC")),
    )


class OutboxEvent(Base):
    __tablename__ = "outbox_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, unique=True
    )
    event_type: Mapped[str] = mapped_column(String(128), nullable=False)
    target_service: Mapped[str] = mapped_column(String(64), nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default=text("'pending'")
    )
    attempts: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    last_error: Mapped[str | None] = mapped_column(Text)
    process_after: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # updated_at: set in app code, not via onupdate - visible at the call site.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index(
            "idx_outbox_pending",
            "status",
            "process_after",
            postgresql_where=text("status IN ('pending', 'processing')"),
        ),
        Index("idx_outbox_event_id", "event_id"),
        Index("idx_outbox_correlation_id", "correlation_id"),
        Index("idx_outbox_created_at", text("created_at DESC")),
    )


class ProcessedEvent(Base):
    __tablename__ = "processed_events"

    event_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True))
    processed_by: Mapped[str] = mapped_column(String(64), nullable=False)
    processed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # Composite PK: the same event_id can be independently marked processed by
    # each service, matching is_already_processed's (event_id, processed_by)
    # lookup. The PK index also serves that lookup, so no separate index needed.
    __table_args__ = (
        PrimaryKeyConstraint("event_id", "processed_by", name="pk_processed_events"),
    )


class RunbookDocument(Base):
    __tablename__ = "runbook_documents"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    runbook_id: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    title: Mapped[str] = mapped_column(String(512), nullable=False)
    file_path: Mapped[str] = mapped_column(String(512), nullable=False)
    services: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default=text("'{}'::text[]")
    )
    severity: Mapped[str | None] = mapped_column(String(32))
    content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    chunk_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("0")
    )
    indexed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    index_status: Mapped[str] = mapped_column(
        String(32), nullable=False, server_default=text("'pending'")
    )
    index_error: Mapped[str | None] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # updated_at: set in app code, not via onupdate - visible at the call site.
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_runbook_docs_runbook_id", "runbook_id"),
        Index("idx_runbook_docs_services", "services", postgresql_using="gin"),
        Index("idx_runbook_docs_index_status", "index_status"),
    )


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=text(_GEN_UUID)
    )
    event_type: Mapped[str] = mapped_column(String(128), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    correlation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False
    )
    actor: Mapped[str | None] = mapped_column(String(128))
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    __table_args__ = (
        Index("idx_audit_entity", "entity_type", "entity_id"),
        Index("idx_audit_correlation_id", "correlation_id"),
        Index("idx_audit_event_type", "event_type"),
        Index("idx_audit_created_at", text("created_at DESC")),
    )
