"""initial schema

Revision ID: a43594b399c6
Revises:
Create Date: 2026-07-07 10:45:31.274502

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a43594b399c6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(length=128), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_audit_correlation_id", "audit_log", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_audit_created_at", "audit_log", [sa.text("created_at DESC")], unique=False
    )
    op.create_index(
        "idx_audit_entity", "audit_log", ["entity_type", "entity_id"], unique=False
    )
    op.create_index("idx_audit_event_type", "audit_log", ["event_type"], unique=False)
    op.create_table(
        "incidents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("service_name", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'open'"),
            nullable=False,
        ),
        sa.Column(
            "alert_count", sa.Integer(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correlation_id"),
    )
    op.create_index(
        "idx_incidents_correlation_id", "incidents", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_incidents_fingerprint", "incidents", ["fingerprint"], unique=False
    )
    op.create_index(
        "idx_incidents_opened_at",
        "incidents",
        [sa.text("opened_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_incidents_service_name", "incidents", ["service_name"], unique=False
    )
    op.create_index("idx_incidents_status", "incidents", ["status"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("target_service", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "process_after",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "idx_outbox_correlation_id", "outbox_events", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_outbox_created_at",
        "outbox_events",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index("idx_outbox_event_id", "outbox_events", ["event_id"], unique=False)
    op.create_index(
        "idx_outbox_pending",
        "outbox_events",
        ["status", "process_after"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("processed_by", sa.String(length=64), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", "processed_by", name="pk_processed_events"),
    )
    op.create_table(
        "runbook_documents",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("runbook_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.Column(
            "services",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "index_status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("index_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("runbook_id"),
    )
    op.create_index(
        "idx_runbook_docs_index_status",
        "runbook_documents",
        ["index_status"],
        unique=False,
    )
    op.create_index(
        "idx_runbook_docs_runbook_id", "runbook_documents", ["runbook_id"], unique=False
    )
    op.create_index(
        "idx_runbook_docs_services",
        "runbook_documents",
        ["services"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "alerts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_alert_id", sa.String(length=256), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("service_name", sa.String(length=128), nullable=False),
        sa.Column("alert_name", sa.String(length=256), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'firing'"),
            nullable=False,
        ),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "labels",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "annotations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("fired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("incident_id", sa.UUID(), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alerts_correlation_id", "alerts", ["correlation_id"], unique=False
    )
    op.create_index("idx_alerts_fingerprint", "alerts", ["fingerprint"], unique=False)
    op.create_index(
        "idx_alerts_fired_at", "alerts", [sa.text("fired_at DESC")], unique=False
    )
    op.create_index("idx_alerts_incident_id", "alerts", ["incident_id"], unique=False)
    op.create_index("idx_alerts_service_name", "alerts", ["service_name"], unique=False)
    op.create_index("idx_alerts_status", "alerts", ["status"], unique=False)
    op.create_table(
        "investigation_plans",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("template_key", sa.String(length=128), nullable=True),
        sa.Column(
            "status",
            sa.String(length=32),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_plans_incident_id", "investigation_plans", ["incident_id"], unique=False
    )
    op.create_index(
        "idx_plans_one_per_incident",
        "investigation_plans",
        ["incident_id"],
        unique=True,
    )
    op.create_table(
        "recommendations",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("llm_provider", sa.String(length=64), nullable=False),
        sa.Column("model_alias", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("root_cause", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column(
            "recommended_actions",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "context_bundle",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("raw_llm_response", sa.Text(), nullable=True),
        sa.Column(
            "is_fallback", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["investigation_plans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rec_correlation", "recommendations", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_rec_created_at",
        "recommendations",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_rec_incident_id", "recommendations", ["incident_id"], unique=False
    )
    op.create_index(
        "idx_rec_is_fallback", "recommendations", ["is_fallback"], unique=False
    )
    op.create_index("idx_rec_plan_id", "recommendations", ["plan_id"], unique=False)
    op.create_table(
        "feedback",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("recommendation_id", sa.UUID(), nullable=False),
        sa.Column("incident_id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("sentiment", sa.String(length=16), nullable=False),
        sa.Column("correction_text", sa.Text(), nullable=True),
        sa.Column("slack_user_id", sa.String(length=64), nullable=True),
        sa.Column("slack_message_ts", sa.String(length=64), nullable=True),
        sa.Column("llm_provider", sa.String(length=64), nullable=False),
        sa.Column("model_alias", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_feedback_created_at",
        "feedback",
        [sa.text("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "idx_feedback_incident_id", "feedback", ["incident_id"], unique=False
    )
    op.create_index(
        "idx_feedback_recommendation_id",
        "feedback",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index("idx_feedback_sentiment", "feedback", ["sentiment"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_feedback_sentiment", table_name="feedback")
    op.drop_index("idx_feedback_recommendation_id", table_name="feedback")
    op.drop_index("idx_feedback_incident_id", table_name="feedback")
    op.drop_index("idx_feedback_created_at", table_name="feedback")
    op.drop_table("feedback")
    op.drop_index("idx_rec_plan_id", table_name="recommendations")
    op.drop_index("idx_rec_is_fallback", table_name="recommendations")
    op.drop_index("idx_rec_incident_id", table_name="recommendations")
    op.drop_index("idx_rec_created_at", table_name="recommendations")
    op.drop_index("idx_rec_correlation", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index("idx_plans_one_per_incident", table_name="investigation_plans")
    op.drop_index("idx_plans_incident_id", table_name="investigation_plans")
    op.drop_table("investigation_plans")
    op.drop_index("idx_alerts_status", table_name="alerts")
    op.drop_index("idx_alerts_service_name", table_name="alerts")
    op.drop_index("idx_alerts_incident_id", table_name="alerts")
    op.drop_index("idx_alerts_fired_at", table_name="alerts")
    op.drop_index("idx_alerts_fingerprint", table_name="alerts")
    op.drop_index("idx_alerts_correlation_id", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(
        "idx_runbook_docs_services",
        table_name="runbook_documents",
        postgresql_using="gin",
    )
    op.drop_index("idx_runbook_docs_runbook_id", table_name="runbook_documents")
    op.drop_index("idx_runbook_docs_index_status", table_name="runbook_documents")
    op.drop_table("runbook_documents")
    op.drop_table("processed_events")
    op.drop_index(
        "idx_outbox_pending",
        table_name="outbox_events",
        postgresql_where=sa.text("status IN ('pending', 'processing')"),
    )
    op.drop_index("idx_outbox_event_id", table_name="outbox_events")
    op.drop_index("idx_outbox_created_at", table_name="outbox_events")
    op.drop_index("idx_outbox_correlation_id", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("idx_incidents_status", table_name="incidents")
    op.drop_index("idx_incidents_service_name", table_name="incidents")
    op.drop_index("idx_incidents_opened_at", table_name="incidents")
    op.drop_index("idx_incidents_fingerprint", table_name="incidents")
    op.drop_index("idx_incidents_correlation_id", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index("idx_audit_event_type", table_name="audit_log")
    op.drop_index("idx_audit_entity", table_name="audit_log")
    op.drop_index("idx_audit_created_at", table_name="audit_log")
    op.drop_index("idx_audit_correlation_id", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
