#!/usr/bin/env bash
# Bootstrap a clean machine for RADAR development.
# Idempotent: safe to run multiple times. Never overwrites an existing .env.
# Security posture:
#   - No secrets are hardcoded in this repo. This script generates random,
#     per-machine credentials into .env (gitignored, chmod 600).
#   - Nothing secret is ever echoed to stdout or logged.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

info() { printf '\033[1;34m[bootstrap]\033[0m %s\n' "$*"; }
fail() { printf '\033[1;31m[bootstrap]\033[0m %s\n' "$*" >&2; exit 1; }

# --- Python -----------------------------------------------------------------
if ! command -v python3 >/dev/null 2>&1; then
    fail "python3 not found. Install Python 3.12 or newer, then re-run."
fi

PYTHON_VERSION="$(python3 -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')"
PYTHON_OK="$(python3 -c 'import sys; print(int(sys.version_info >= (3, 12)))')"
if [ "$PYTHON_OK" != "1" ]; then
    fail "Python >= 3.12 required, found $PYTHON_VERSION."
fi
info "Python $PYTHON_VERSION found."

# --- uv ---------------------------------------------------------------------
if ! command -v uv >/dev/null 2>&1; then
    info "uv not found. Installing via https://astral.sh/uv ..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.local/bin:$PATH"
    command -v uv >/dev/null 2>&1 || fail "uv install failed. Install manually: https://docs.astral.sh/uv/"
fi
info "uv $(uv --version | awk '{print $2}') found."

# --- Docker -----------------------------------------------------------------
if ! command -v docker >/dev/null 2>&1; then
    fail "docker not found. Install Docker Desktop (macOS) or Docker Engine (Linux), then re-run."
fi
if ! docker info >/dev/null 2>&1; then
    fail "docker daemon is not running. Start Docker, then re-run."
fi
if ! docker compose version >/dev/null 2>&1; then
    fail "docker compose plugin not found. Install Docker Compose v2, then re-run."
fi
info "Docker $(docker version --format '{{.Server.Version}}') found."

# --- .env with generated secrets ---------------------------------------------
gen_secret() {
    python3 -c 'import secrets; print(secrets.token_hex(32))'
}

if [ ! -f .env ]; then
    info "Generating .env with random per-machine credentials..."

    POSTGRES_USER="radar"
    POSTGRES_DB="radar"
    POSTGRES_PASSWORD="$(gen_secret)"
    VAULT_DEV_ROOT_TOKEN="$(gen_secret)"
    GRAFANA_ADMIN_PASSWORD="$(gen_secret)"

    umask 077
    cat > .env <<EOF
# Generated by scripts/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# This file contains secrets. It is gitignored. Do not commit, copy, or share it.

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_DSN=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}
VAULT_DEV_ROOT_TOKEN=${VAULT_DEV_ROOT_TOKEN}
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

ELASTICSEARCH_URL=http://localhost:9200
VAULT_ADDR=http://localhost:8200

# External credentials: fill these in yourself. Never commit them anywhere.
OPENAI_API_KEY=__SET_ME__
SLACK_BOT_TOKEN=__SET_ME__
SLACK_APP_TOKEN=__SET_ME__
EOF
    chmod 600 .env

    unset POSTGRES_PASSWORD VAULT_DEV_ROOT_TOKEN GRAFANA_ADMIN_PASSWORD
    info "Created .env (mode 600). Secrets were generated, not defaults."
    info "Edit .env to add your OPENAI_API_KEY and SLACK_* tokens."
else
    chmod 600 .env
    info ".env already exists. Leaving contents untouched (permissions enforced to 600)."
fi

# --- Dependencies and hooks ----------------------------------------------------
info "Running make setup (uv sync + pre-commit install)..."
make setup

info "Bootstrap complete."
info "Next steps:"
info "  1. Edit .env with real external credentials (OPENAI_API_KEY, SLACK_*)."
info "  2. Run 'make dev' to start the local stack."
